config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :tasks, only: %i[ index new create edit update destroy]
end

#index new create show edit update destroy

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, length: { maximum: 25, minimum: 1 } 
  validates :status, presence: true

  enum status: {
    to_do: 'A fazer',
    in_progress: 'Em progresso',
    completed: 'Concluída'
  }, _suffix: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :fetch_task, only: %i[ edit update destroy ]
  before_action :get_status
  
  def index
    @tasks = Task.all.order(created_at: :asc)
    @no_tasks_message = "Não há tarefas criadas no momento." if @tasks.empty?
  end
  
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    return redirect_to tasks_path if @task.save
  end

  def edit
    @task = Task.find(params[:id])
    render partial: 'tasks/shared/form', locals: { model: @task, url: task_path(@task), method: :patch }, layout: false  
  end

  def update
    return redirect_to tasks_path if @task.update(task_params)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def get_status
    @task_status = Task.statuses
  end

  def fetch_task 
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(date)
    I18n.l(date, format: "%-d de %B de %Y - %H:%M")
  end
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <h2> Home </h2>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lista de Tarefas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>

        <div class="container mt-4">
        
            <h2> Tarefas </h2>

            <%= link_to new_task_path, remote: false, class: "btn create-button w-100 mb-2 rounded-bottom-0", data: {bs_toggle: "modal", bs_target: "#create-task-modal" } do %>
                <i class="bi bi-calendar-plus-fill"></i>
            <% end %>

            <% if @no_tasks_message %>
                <div class="error-message-box">
                    <lord-icon
                        src="https://cdn.lordicon.com/abfverha.json"
                        trigger="in"
                        delay="200"
                        state="in-calendar"
                        colors="primary:#ffffff"
                        style="width:250px;height:150px">
                    </lord-icon>
                    <h3 class="fs-5 no_tasks_message d-flex justify-content-center my-4">Nenhuma tarefa registrada no momento.</h3>
                </div>
            <% else %>
                <table class="table table-tasks table-striped table-hover table-responsive text-center align-middle mt-2">
                    <thead>
                        <tr>
                            <th scope="col" class="col-2">Tarefa</th>
                            <th scope="col" class="col-3">Criada em</th>
                            <th scope="col" class="col-1">Status</th>
                            <th scope="col" class="col-2">Ações</th>
                        </tr>
                    </thead>

                    <tbody>
                        <% @tasks.each do |task| %>
                            <tr>
                                <td scope="row"><%= task.name %></td>
                                <td><%= format_date(task.created_at) %></td>
                                <td><%= task.status_before_type_cast.humanize %></td>
                                <td class="d-flex align-items-center justify-content-center gap-1 flex-column flex-md-row">
                                <%= link_to "#", class: "text-decoration-none", data: { bs_toggle: "modal", bs_target: "#edit-task-modal", task_id: task.id } do %>
                                    <div class="edit-button rounded-2 d-flex align-items-center justify-content-center">
                                    <lord-icon
                                        src="https://cdn.lordicon.com/exymduqj.json"
                                        trigger="hover"
                                        stroke="bold"
                                        state="hover-line"
                                        colors="primary:#fff,secondary:#fff"
                                        style="width:20px;height:20px;">
                                    </lord-icon>
                                    </div>
                                <% end %>
                        
                                <%= render partial: '/tasks/shared/modal_edit', locals: { model: task, url: edit_task_path(task), method: :patch } %>
                                <%= button_to task_path(task), class: "button-index text-decoration-none d-flex", method: :delete do %>
                                    <div class="delete-button rounded-2 d-flex align-items-center justify-content-center">
                                    <lord-icon
                                        src="https://cdn.lordicon.com/hwjcdycb.json"
                                        trigger="morph"
                                        stroke="bold"
                                        state="morph-trash-in"
                                        colors="primary:#ffffff,secondary:#ffffff"
                                        style="width:20px;height:20px">
                                    </lord-icon>
                                    </div>
                                <% end %>
                                </td>
                            </tr>
                            <% end %>

                    </tbody>
                    
                </table>
            <% end %>

            <div class="footer-block w-100 rounded-2 rounded-top-0"></div>

        </div>
        
        <%= render partial: '/tasks/shared/modal_edit', locals: { model: Task, url: tasks_path, method: :post } %>
        <%= render partial: '/tasks/shared/modal_new', locals: { model: Task, url: tasks_path, method: :post } %>
    </body>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.lordicon.com/lordicon.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            const editModal = document.getElementById('edit-task-modal');
        
            editModal.addEventListener('show.bs.modal', function(event) {
            const button = event.relatedTarget; 
            const taskId = button.getAttribute('data-task-id');
        
            const url = `/tasks/${taskId}/edit`;
        
            fetch(url)
                .then(response => response.text())
                .then(html => {
                document.getElementById('modalBody').innerHTML = html;
                })
                .catch(error => console.error('Erro ao carregar o formulário:', error));
            });
        });
    </script>
</html>

app/views/tasks/shared/_form.html.erb
<%= form_with(model: model, url: url, method: method, local: true) do |f| %>
  <div class="form-floating mb-3">
    <%= f.text_field :name, class: "form-control", id: "floatingInputGrid", autocomplete: "off", required: true %>
    <%= f.label :name, "Nome da Tarefa", for: "floatingInputGrid" %>
  </div>

  <div class="form-floating mb-3">
    <%= f.select :status, @task_status.map { |option| [option.second, option.first] }, {}, class: "form-select", id: "floatingSelectGrid" %>
    <%= f.label :status, "Status", for: "floatingSelectGrid" %>
  </div>

  <div class="d-flex justify-content-end">
    <%= f.submit method.eql?(:post) ? 'Criar' : 'Salvar', class: "btn btn-form-custom" %>
  </div>
<% end %>

app/views/tasks/shared/_modal_edit.html.erb
 <div class="modal fade" id="edit-task-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Editar Tarefa</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modalBody">
                 <%= render partial: "tasks/shared/form", locals: { model: model, url: task_path(model), method: :put } %>
            </div>
        </div>
    </div>
</div>

app/views/tasks/shared/_modal_new.html.erb
 <div class="modal fade" id="create-task-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Criar Tarefa</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modalBody">
                <%= render partial: "tasks/shared/form", locals: { model: Task.new, url: url, method: :post } %>
            </div>
        </div>
    </div>
</div>